# Generated by Django 3.1.2 on 2021-04-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kedia', '0002_auto_20210415_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='icon_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
