# Generated by Django 3.1.2 on 2021-04-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kedia', '0003_pricing_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='Projects/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=65500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
